# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

project 'MUIPopMenuDemo.xcodeproj'
 
def dependency

    pod 'Masonry'
    pod 'pop'

end
 
def develop_dependency 

end

target 'MUIPopMenuDemo' do
    
    dependency
    develop_dependency
end

target 'MUIPopMenuDemoTests' do
    
    dependency
    develop_dependency
    
end

target 'MUIPopMenuDemoUITests' do
    
    dependency
    develop_dependency
    
end
